### ISSUE TITLE
Order of the nodes in the tree layer

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-viewer-app#43] opened 2024-09-06 13:50 UTC
**Describe the bug**
The layer tree that appears in the SITMUN viewer should be exactly the same (with the exact same order) that the one defined in SITMUN admin.

**To Reproduce**
1. Compare, for any viewers with multiple layers and folders, the tree in the layer tree defined in SITMUN admin an the one presented by SITMUN viewer. 

**Screenshots**

![imagen](https://github.com/user-attachments/assets/f32c53e0-160b-4d66-ade8-770f27c41807)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fjlopez** [comment] 2024-09-09 10:38
Is this problem the same or duplicate of... ?

- https://github.com/sitmun/sitmun-viewer-app/issues/8

@silmeUsil0001 , if so, I thought that this was solved. Can you confirm this?

**Closed** 2024-10-18 09:57 UTC
Labels: duplicate
